name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: apt update && apt install -y libgirepository1.0-dev libgtk-3-dev
    - name: Install dependencies
      run: shards install
    - name: Run tests
      uses: GabrielBB/xvfb-action@v1.0
      with:
        run: script/ci.sh
